### ISSUE TITLE
npm start / npm run pro fail - Error: ENOENT: no such file or directory, lstat 'node_modules/bootstrap/fonts'

### ISSUE THREAD

**Issue by butchmarshall** [dherrero/angularjs-es6-starter#1]
(rollup-plugin-copy) 'node_modules/bootstrap/fonts' -> 'fonts/' (✘)

    Error: ENOENT: no such file or directory, lstat 'node_modules/bootstrap/fonts'
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! cme-admin@1.0.0 dev-watch: `rollup -c rollup.config.dev.js --watch`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the cme-admin@1.0.0 dev-watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dherrero** [comment]
I'm sorry I'm late, the project is out of date. I changed the bootstrap version without even trying. I left the version as it was, it should work with a nodejs 6.
When I have time I will update the project, for now I keep it as deprecated.
Sorry again
